In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.abs([-1, 2, 3])

array([1, 2, 3])

In [6]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## funciones de agregación

In [12]:
arr = np.random.randn(6,4)

In [13]:
arr

array([[ 1.14227258,  0.41521973, -0.78511608, -1.11057296],
       [ 0.61227642,  1.09203405,  0.50132217,  0.03292528],
       [-0.06227543,  0.64117282, -0.61390211,  1.91812426],
       [-0.44882712,  2.10660949, -0.56636696, -0.98014024],
       [ 0.64247655, -0.03871369, -0.17637853, -0.0965718 ],
       [-1.65299075,  0.70556685, -0.84231127,  0.02096516]])

In [14]:
arr.mean()

0.10236660063889562

In [15]:
arr.sum()

2.4567984153334947

In [17]:
arr.prod()

9.828180797059795e-10